version: '3'

services:

  main:
    image: registry.torpedo.red:5000/hello-world-boot:0.1
    environment:
      - LISTEN_PORT=8080
    networks:
      - default
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/spring
        - com.df.port=8080


networks:
  default:
    external: false
